language: node_js

node_js: 
  - "12"
  - "10"

env:
  - NODE_ENV=development PORT=3000 MONGO_HOST=mongodb://travis:test@127.0.0.1/unit_testing


services:
  - mongodb

before_script:
  - sleep 15
  - mongo unit_testing --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - mongo unit_testing --eval 'db.users.insert([{username:"j.y", password:"pass123" }, {username:"chung",password:"pass123" },{username:"simon",password:"pass123" }]);'